# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

pool:
  vmImage: 'Ubuntu 16.04'

steps:
- script: curl https://sh.rustup.rs -sSf | sh
  displayName: 'install rust'

- script: |
    export PATH="~/.cargo/bin:$PATH"
    if command -v rustup >/dev/null; then
      rustup install stable-x86_64-unknown-linux-gnu
    else
        curl https://sh.rustup.rs -sSf | sh -s -- --default-toolchain stable-x86_64-unknown-linux-gnu -y
    fi
    rustup install nightly-x86_64-unknown-linux-gnu
  displayName: Install Rust
- script: |
    export PATH="~/.cargo/bin:$PATH"
    cargo +nightly-x86_64-unknown-linux-gnu install rustfmt-nightly --force
    cargo +nightly-x86_64-unknown-linux-gnu fmt -- --write-mode diff
  displayName: Validate Formatting
- script: |
    export PATH="~/.cargo/bin:$PATH"
    cargo +nightly-x86_64-unknown-linux-gnu test
  displayName: Run Tests
- script: |
    export PATH="~/.cargo/bin:$PATH"
    cargo +nightly-x86_64-unknown-linux-gnu build --release
  displayName: Build Release
